# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: teleport CI

on:
  push:
    branches: [ master ]
    pull_request:
      branches: [ master ]
jobs:

  python_test_runner:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '2.x'

    - name: Display the google sdk path path
      run: gcloud info --format="value(installation.sdk_root)"

    # You can test your matrix by printing the current Python version
    - name: install packages
      run: |
        python -m pip install --upgrade pip
        pip install -t server/lib -r requirements.txt
        pip install coverage

    - name: Adding SDK components
      run: sudo apt-get install google-cloud-sdk-datastore-emulator google-cloud-sdk-app-engine-python google-cloud-sdk-app-engine-python-extras google-cloud-sdk

    - name: run python test cases
      run: |
        coverage run server-tests/runner.py /usr/lib/google-cloud-sdk
        coverage report
        coverage xml